language: cpp
compiler: gcc


notifications:
  email: false

addons:
  apt:
    sources:
      - sourceline: ppa:beineri/opt-qt-5.10.1-trusty
    packages:
      - realpath
      - wget
      - git
      - realpath
      - cmake
      - desktop-file-utils
      - qt510-meta-minimal


script:
  - /opt/qt510/bin/qt510-env.sh
  - sudo update-alternatives --install /usr/bin/qmake qmake /opt/qt510/bin/qmake 1
  - cmake . -DCMAKE_INSTALL_PREFIX=/usr
  - make install -j`nproc` DESTDIR=AppDir

  # Build Appimage
  - wget -nc https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  - wget -nc https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage

  - chmod +x linuxdeploy-*
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/qt510/lib
  - ./linuxdeploy-x86_64.AppImage --appdir=AppDir --plugin qt --output appimage

after_success:
  - ls -lh
  # make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
  - if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh rundialog-qt*.AppImage*
