language: cpp
compiler: gcc


notifications:
  email: false

addons:
  apt:
    packages:
      - realpath
      - wget
      - git
      - realpath
      - cmake
      - desktop-file-utils
      - pkg-config
      - build-essential

install:
  # Install conan
  - sudo wget -qnc https://github.com/azubieta/conan-appimage/releases/download/continuous/conan-8e5c23a-x86_64.AppImage -O /usr/bin/conan
  - sudo chmod a+x /usr/bin/conan

  # Configure conan remotes
  - conan remote add appimage ${APPIMAGE_REPO_URL} --insert
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
  - conan install . --build missing -g virtualrunenv
  - source activate_run.sh
  - cmake . -DCMAKE_INSTALL_PREFIX=/usr
  - make install -j`nproc` DESTDIR=AppDir

  # Build Appimage
  - wget -nc https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  - wget -nc https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage

  - chmod +x linuxdeploy-*
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/AppDir/usr/lib
  - ./linuxdeploy-x86_64.AppImage --appdir=AppDir --plugin qt --output appimage

after_success:
  - ls -lh
  # make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
  - if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh rundialog-qt*.AppImage*
